# Python (Pandas) - Testovací cvičení (Loans Dataset)

V tomto sešitu plníme kroky analýzy a předzpracování datasetu `loans.csv`:
1. Načtení dat pomocí Pandas
2. Přejmenování sloupců na malá písmena
3. Zobrazení prvních 10 pozorování
4. Kontrola a konverze datových typů
5. Kontrola chybějících hodnot pomocí `.isnull()`
6. Nahrazení chybějících hodnot u kategoriálních proměnných nejčastější hodnotou (`.mode()`)
7. Výběr schválených půjček (`loans_granted`)
8. Výběr schválených půjček samostatným žadatelům (`standalone_borrowers`)
9. Agregace podle pohlaví (`loans_count_by_gender`)

## 1. Načtení knihovny Pandas a datasetu loans.csv

In [1]:
import pandas as pd
import os

# Načtení datasetu
data_path = os.path.join("data", "loans.csv") if os.path.exists(os.path.join("data", "loans.csv")) else os.path.join("00_Prework", "data", "loans.csv")
df = pd.read_csv(data_path)
print(f"Rozměry datasetu: {df.shape[0]} řádků, {df.shape[1]} sloupců")

Rozměry datasetu: 614 řádků, 12 sloupců

## 2. Přejmenování sloupců na malá písmena

In [2]:
df.columns = df.columns.str.lower()
print("Sloupce:", df.columns.tolist())

Sloupce: ['gender', 'married', 'dependents', 'education', 'self_employed', 'applicant_income', 'coapplicant_income', 'loan_amount', 'term', 'credit_history', 'area', 'status']

## 3. Zobrazení prvních 10 řádků

In [3]:
df.head(10)

,gender,married,dependents,education,self_employed,applicant_income,coapplicant_income,loan_amount,term,credit_history,area,status
0,Male,No,0,Graduate,No,584900,0.0,15000000,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,458300,150800.0,12800000,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,300000,0.0,6600000,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,258300,235800.0,12000000,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,600000,0.0,14100000,360.0,1.0,Urban,Y
5,Male,Yes,2,Graduate,Yes,541700,419600.0,26700000,360.0,1.0,Urban,Y
6,Male,Yes,0,Not Graduate,No,233300,151600.0,9500000,360.0,1.0,Urban,Y
7,Male,Yes,3+,Graduate,No,303600,250400.0,15800000,360.0,0.0,Semiurban,N
8,Male,Yes,2,Graduate,No,400600,152600.0,16800000,360.0,1.0,Urban,Y
9,Male,Yes,1,Graduate,No,1284100,1096800.0,34900000,360.0,1.0,Semiurban,N

## 4. Kontrola a konverze datových typů

In [4]:
# Výpis původních datových typů
print(df.dtypes)

# Konverze kategoriálních proměnných na category
cat_cols = ['gender', 'married', 'education', 'self_employed', 'area', 'status']
for col in cat_cols:
    df[col] = df[col].astype('category')

df.info()

gender                    str
married                   str
dependents                str
education                 str
self_employed             str
applicant_income        int64
coapplicant_income    float64
loan_amount             int64
term                  float64
credit_history        float64
area                      str
status                    str
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              601 non-null    category
 1   married             611 non-null    category
 2   dependents          599 non-null    str
 3   education           614 non-null    category
 4   self_employed       582 non-null    category
 5   applicant_income    614 non-null    int64
 6   coapplicant_income  614 non-null    float64
 7   loan_amount         614 non-null    int64
 8   term                600 non-null    float64
 9   credit_history      564 non-null    float64
 10  area                614 non-null    category
 11  status              614 non-null    category
dtypes: category(6), float64(3), int64(2), str(1)
memory usage: 32.7 KB

## 5. Počet chybějících hodnot (.isnull())

In [5]:
df.isnull().sum()

gender                13
married                3
dependents            15
education              0
self_employed         32
applicant_income       0
coapplicant_income     0
loan_amount            0
term                  14
credit_history        50
area                   0
status                 0
dtype: int64

## 6. Nahrazení chybějících hodnot u kategoriálních proměnných nejčastější hodnotou (.mode())

In [6]:
categorical_to_impute = ['gender', 'married', 'dependents', 'self_employed']

for col in categorical_to_impute:
    mode_val = df[col].mode()[0]
    df[col] = df[col].fillna(mode_val)
    print(f"Sloupec '{col}' doplněn módem: '{mode_val}'")

# Doplnění módu i pro credit_history (binární ukazatel 0/1)
df['credit_history'] = df['credit_history'].fillna(df['credit_history'].mode()[0])

# Kontrola
df.isnull().sum()

Sloupec 'gender' doplněn módem: 'Male'
Sloupec 'married' doplněn módem: 'Yes'
Sloupec 'dependents' doplněn módem: '0'
Sloupec 'self_employed' doplněn módem: 'No'

gender                 0
married                0
dependents             0
education              0
self_employed          0
applicant_income       0
coapplicant_income     0
loan_amount            0
term                  14
credit_history         0
area                   0
status                 0
dtype: int64

## 7. loans_granted – schválené půjčky (status == 'Y')

In [7]:
loans_granted = df[df['status'] == 'Y'].copy()
print(f"Počet schválených půjček: {len(loans_granted)}")
loans_granted.head()

Počet schválených půjček: 422

,gender,married,dependents,education,self_employed,applicant_income,coapplicant_income,loan_amount,term,credit_history,area,status
0,Male,No,0,Graduate,No,584900,0.0,15000000,360.0,1.0,Urban,Y
2,Male,Yes,0,Graduate,Yes,300000,0.0,6600000,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,258300,235800.0,12000000,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,600000,0.0,14100000,360.0,1.0,Urban,Y
5,Male,Yes,2,Graduate,Yes,541700,419600.0,26700000,360.0,1.0,Urban,Y

## 8. standalone_borrowers – schválené půjčky samostatným žadatelům
Samostatný žadatel (standalone applicant) žádá o půjčku sám, bez spolužadatele (`coapplicant_income == 0`).

In [8]:
standalone_borrowers = loans_granted[loans_granted['coapplicant_income'] == 0].copy()
print(f"Počet schválených půjček samostatným žadatelům: {len(standalone_borrowers)}")
standalone_borrowers.head()

Počet schválených půjček samostatným žadatelům: 177

,gender,married,dependents,education,self_employed,applicant_income,coapplicant_income,loan_amount,term,credit_history,area,status
0,Male,No,0,Graduate,No,584900,0.0,15000000,360.0,1.0,Urban,Y
2,Male,Yes,0,Graduate,Yes,300000,0.0,6600000,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,600000,0.0,14100000,360.0,1.0,Urban,Y
15,Male,No,0,Graduate,No,495000,0.0,12500000,360.0,1.0,Urban,Y
16,Male,No,1,Not Graduate,No,359600,0.0,10000000,240.0,1.0,Urban,Y

## 9. loans_count_by_gender – statistiky podle pohlaví
Spočítáme:
- počet půjček podle pohlaví
- průměrný příjem žadatele (`applicant_income`)
- průměrnou výši půjčky (`loan_amount`)

In [ ]:
loans_count_by_gender = loans_granted.groupby('gender', observed=False).agg(
    loans_count=('loan_amount', 'count'),
    avg_applicant_income=('applicant_income', 'mean'),
    avg_loan_amount=('loan_amount', 'mean')
).reset_index()

loans_count_by_gender['avg_applicant_income'] = loans_count_by_gender['avg_applicant_income'].round(2)
loans_count_by_gender['avg_loan_amount'] = loans_count_by_gender['avg_loan_amount'].round(2)

loans_count_by_gender

   gender  loans_count  avg_applicant_income  avg_loan_amount
0  Female           75             491585.33      12236000.00
1    Male          347             548526.80      14489337.18

: